// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_ZNCdS1jkVMeuKaxrmHLZPiSEUR6BzA',
    appId: '1:606307895398:web:ccb4feabfc0a953ab985a7',
    messagingSenderId: '606307895398',
    projectId: 'calendar-event-7b656',
    authDomain: 'calendar-event-7b656.firebaseapp.com',
    storageBucket: 'calendar-event-7b656.firebasestorage.app',
    measurementId: 'G-1TNHYNQ9ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8m9TN2vZzAcGYmez015FO6Cu3k83GjKc',
    appId: '1:606307895398:android:9acf7a2d3733e0d7b985a7',
    messagingSenderId: '606307895398',
    projectId: 'calendar-event-7b656',
    storageBucket: 'calendar-event-7b656.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-YFbLKGUFTeX0He6cAfzRhlfIunnNEo',
    appId: '1:606307895398:ios:333d10019a09d8dab985a7',
    messagingSenderId: '606307895398',
    projectId: 'calendar-event-7b656',
    storageBucket: 'calendar-event-7b656.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-YFbLKGUFTeX0He6cAfzRhlfIunnNEo',
    appId: '1:606307895398:ios:333d10019a09d8dab985a7',
    messagingSenderId: '606307895398',
    projectId: 'calendar-event-7b656',
    storageBucket: 'calendar-event-7b656.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl_ZNCdS1jkVMeuKaxrmHLZPiSEUR6BzA',
    appId: '1:606307895398:web:44a8d86eb05df458b985a7',
    messagingSenderId: '606307895398',
    projectId: 'calendar-event-7b656',
    authDomain: 'calendar-event-7b656.firebaseapp.com',
    storageBucket: 'calendar-event-7b656.firebasestorage.app',
    measurementId: 'G-3DQGS1W1DN',
  );
}
